name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server:
          - mariadb-server
          - mysql-server
    steps:
      - uses: actions/checkout@v3
      - name: Install ${{ matrix.server }}
        run: sudo apt-get install -y --no-install-recommends ${{ matrix.server }}
      - name: Install bats
        run: sudo apt-get install -y --no-install-recommends bats
      - name: Run tests
        run: bats --tap my_virtualenv.bats
